export interface VideoInfo {
    vod_id: number,
    type_id: number,
    type_id_1: number,
    group_id: number,
    vod_name: string,
    vod_sub: string,
    vod_en: string,
    vod_status: number,
    vod_letter: string,
    vod_color: string,
    vod_tag: string,
    vod_class: string,
    vod_pic: string,
    vod_pic_thumb: string,
    vod_pic_slide: string,
    vod_pic_screenshot: string,
    vod_actor: string,
    vod_director: string,
    vod_writer: string,
    vod_behind: string,
    vod_blurb: string,
    vod_remarks: string,
    vod_pubdate: string,
    vod_total: number,
    vod_serial: number,
    vod_tv: string,
    vod_weekday: string,
    vod_area: string,
    vod_lang: string,
    vod_year: number,
    vod_version: string,
    vod_state: string,
    vod_author: string,
    vod_jumpurl: string,
    vod_tpl: string,
    vod_tpl_play: string,
    vod_tpl_down: string,
    vod_isend: number,
    vod_lock: number,
    vod_level: number,
    vod_copyright: number,
    vod_points: number,
    vod_points_play: number,
    vod_points_down: number,
    vod_hits: number,
    vod_hits_day: number,
    vod_hits_week: number,
    vod_hits_month: number,
    vod_duration: string,
    vod_up: number,
    vod_down: number,
    vod_score: number,
    vod_score_all: number,
    vod_score_num: number,
    vod_time: number,
    vod_time_add: number,
    vod_time_hits: number,
    vod_time_make: number,
    vod_trysee: number,
    vod_douban_id: number,
    vod_douban_score: number,
    vod_reurl: string,
    vod_rel_vod: string,
    vod_rel_art: string,
    vod_pwd: string,
    vod_pwd_url: string,
    vod_pwd_play: string,
    vod_pwd_play_url: string,
    vod_pwd_down: string,
    vod_pwd_down_url: string,
    vod_content: string,
    vod_play_server: string,
    vod_play_note: string,
    vod_down_from: string,
    vod_down_server: string,
    vod_down_note: string,
    vod_down_url: string,
    vod_plot: number,
    vod_plot_name: string,
    vod_plot_detail: string,
    vod_play_list: playVideo[],
    vod_down_list: [],
    vod_plot_list: [],
    vod_pic_screenshot_list: [],
    is_collection: 0,
    ulog_id: 0
}

interface playVideo {
    sid: number,
    player_info: playerInfo,
    server_info: string,
    from: string,
    url: string,
    server: string,
    note: string,
    url_count: number,
    urls: videoUrls[],
}

interface videoUrls {
    name: string,
    url: string,
    from: string,
    nid: number,
}

interface playerInfo {
    status: number,
    from: string,
    show: string,
    des: string,
    target: string,
    ps: number,
    parse: string,
    sort: number,
    tip: string,
    id: string,
}

